# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: WordPress Vocabulary blocks
# All technologies used
technologies: Javascript, React, WordPress
# Whether this repository should be featured on the CC Open Source site
featured: false
